### ISSUE TITLE
Erroneous results and a failure to evaluate with variations on the "scalar" example

### ISSUE THREAD

**Issue by arjenmarkus** [FluidNumerics/feq-parse#12]
Here is the code that gave unexpected and erroneous results (as I mentioned on Fortran discourse, dd. 1 december 2023):

`program scalar_with_scalar_eval

  use FEQParse

  implicit none
  type(EquationParser) :: f
  character(LEN=1),dimension(2) :: independentVars
  character(LEN=30) :: eqChar
  real :: x(2)

  ! Specify the independent variables
  independentVars = (/'x', 'a'/)

  ! Specify an equation string that we want to evaluate
  eqChar = 'f = \exp( -(x^2) ) - a'
!  eqChar = 'f = \exp( -(x^2) - a )'
!  eqChar = 'f = (x - a)^2 )'

  ! Create the EquationParser object
  f = EquationParser(eqChar,independentVars)

  ! Evaluate the equation
  x(1) = 1.0
  x(2) = 1.0
  print*, f % evaluate(x)

  ! Clean up memory
  call f % Destruct()

end program scalar_with_scalar_eval
`
The first expression gives 1, where e^-2 is expected.
The second one (now in comment) gives "Attempt made to pop from empty stack".
The third one (again commented) does give the right answer.

**Comment by fluidnumerics-joe** [comment]
I've added a branch `bugfix/issue-12` to work on this. 
The result you would expect here is "e^-1 -1" (not e^-2). You can run the example that you've provided on this branch with fpm,

```
fpm run --example "gaussian_scalar_multivar"
Project is up to date
 -0.632120550    
 -0.632120550    
```

Are you using the Intel compilers on your system ?

**Comment by fluidnumerics-joe** [comment]
@arjenmarkus - I've got Windows with gfortran 13 builds working just fine [See these tests]( https://github.com/FluidNumerics/feq-parse/pull/13/checks?sha=c1ba2c5aac0e47d09bd201358ca727f66b939c3e )

There's some odd behavior with the `ifx` compiler from Intel OneAPI that I'm working on sorting out still. I've also added memory checks with valgrind to the CI, so we'll see if this turns up anything obvious as we check across compilers.

**Comment by fluidnumerics-joe** [comment]
@arjenmarkus - I just pushed a commit to the bugfix/issue-12 branch that resolves the segmentation faults with the `ifort` and `ifx` compilers when built with CMake. Would you be able to check it out and let me know if this resolves your issue ?

**Comment by arjenmarkus** [comment]
Yes, that seems to do the trick :). The results are in agreement with a
manual calculation and the problem with the empty stack is gone. I did see
that the testsuite program returns a non-zero value, but that may be
unrelated to the library.

Op wo 6 dec 2023 om 20:44 schreef Joe Schoonover ***@***.***>:

**Comment by fluidnumerics-joe** [comment]
@arjenmarkus - I'll check that out. I usually run with `ctest`, rather than running the `testsuite` executable directly. I'll let you know what I find
